### ISSUE TITLE
사용자 인증 설정

### ISSUE THREAD

**Issue by sanchaehwa** [sanchaehwa/Spring_ToyProject1#6]
### ERROR  발생
```
2024-08-28T00:51:51.612+09:00 ERROR 40600 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.IllegalArgumentException: Unexpected user
	at me.hwayeong.springbootdeveloper.service.UserService.lambda$findByEmail$1(UserService.java:32) ~[main/:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at me.hwayeong.springbootdeveloper.service.UserService.findByEmail(UserService.java:32) ~[main/:na]
	at 
```

- UserTable 확인
- UserService 확인
- DB 확인
- Google Console Setting 값 확인
- OAuth2 Handler(*Setting)  , Cookie Setting 확인

**Comment by sanchaehwa** [comment]
Google Login 을 시도하면 H2 DataBase에 값(Email, User,)이 올라오지 않는 문제점 발생.
-> H2 DataBase 가 아닌, MySQL DB 또는 PostgreSQL로 변경해볼 예정
